name: base_box
description: >
  A customizable Flutter widget for building reusable and consistent UIs with less boilerplate.
version: 1.0.2
homepage: https://github.com/parham-pourheidar/base_box
repository: https://github.com/parham-pourheidar/base_box
issue_tracker: https://github.com/parham-pourheidar/base_box/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



