name: base_box
description: "A new Flutter project."
version: 1.0.0
homepage: https://github.com/shervin-h/progress_line
repository: https://github.com/shervin-h/progress_line
issue_tracker: https://github.com/shervin-h/progress_line/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



